DELETE http://localhost:3003/api/blogs/60ae8beea12816399028179d
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9sZCIsImlkIjoiNjBhZTgzZGQxY2JhYTEzNmQ4NTU5NzI2IiwiaWF0IjoxNjIyMTM3MTM5fQ.Uy0-12NoSQxgKjUCng5fg92x9XJvwZxZWOYgGPXOTlA

{}